### ISSUE TITLE
Problème Formatage Annotation Json Api

### ISSUE THREAD

**Issue by Desmondmies** [MasterDID2022/projet-s2#76]
**Problème :**
Actuellement le frontend envoie côté backend les annotations au format 
```
String inputJson = "{\n" +
                "  \"idEpigraphe\":\"1\",\n" +
                "  \"idAnnotation\":\"42\",\n" +
                "  \"annotations\": [\n" +
                "    \"1\": [ x, y, width, height ],\n" +
                "    \"2\": [ x, y, width, height ],\n" +
                "    \"3\": [ x, y, width, height ]\n" +
                "  ]\n" +
                "}"
```

Alors que côté backend l'api reçoit l'annotation en essayant de la parser en format 
```
String inputJson = "{\n" +
                "  \"idEpigraphe\":\"1\",\n" +
                "  \"idAnnotation\":\"42\",\n" +
                "  \"annotations\":{\n" +
                "    \"1\":\n" +
                "      \"x\":[1,2],\n" +
                "      \"y\":[4,2]\n" +
                "    },\n" +
                "    \"2\":{\n" +
                "    },\n" +
                "    \"3\":{\n" +
                "      \"x\":[1,2],\n" +
                "      \"y\":[4,2]\n" +
                "    },\n" +
                "  }\n" +
                "}"
```

**Solution :**
Modifier le formatage de l'api backend, pour parser les x, y, width, height en liste de points et convertir correctement en entités points pour l'Annotation et le stockage avec jpa
Donc stocker dans ce nouveau format :
```
String inputJson = "{\n" +
                "  \"idEpigraphe\":\"1\",\n" +
                "  \"idAnnotation\":\"42\",\n" +
                "  \"annotations\": [\n" +
                "    \"1\": [ [x1, y1], [x2, y2], [x3, y3], [x4, y4] ],\n" +
                "    \"2\": [ [x1, y1], [x2, y2], [x3, y3], [x4, y4] ],\n" +
                "    \"3\":[ [x1, y1], [x2, y2], [x3, y3], [x4, y4] ]\n" +
                "  ]\n" +
                "}"
```

Donc pour convertir d'un `rectangle [x, y, width, height]` vers les `points [ [x1, y1], [x2, y2], [x3, y3], [x4, y4] ]` (ces 4 points correspondent au 4 coin d'un rectangle d'une annotation).
Il suffit de `calculer les 4 points en fonction de x, y et width et height`, côté backend dans l'Api, pour ensuite renvoyer l'objet Annotation correctement construit avec chaque points défini correctement, pour un stockage ultérieur en bdd.

**Comment by anastygnome** [comment]
Je prends le relai sur cette issue. 

Je pense qu'il est plus judicieux de le stocker directement dans le bon format : en effet, en travaillant sur #82, je me suis rendu compte que l'on pourra stocker directement dans le format (Centre, longueur, Largeur) dans une base de donnée avec SIG
