### ISSUE TITLE
Feature de Signalement d'Épigraphie

### ISSUE THREAD

**Issue by Desmondmies** [MasterDID2022/projet-s2#77]
**Description :**
L'utilisateur doit pouvoir signaler une épigraphie en cas de soucis  tel que

- Annotation invalide.
- l'image de l'épigraphie invalide (mauvais format / photographie difficilement lisible) 
- Transcription indisponible

Donc à prévoir dans l'interface de visualisation d'épigraphie un bouton de signalement

**Exigence :**
- [ ] partie UI : un bouton de signalement + une page de consultation des signalements pour le gestionnaire
- [ ] partie API : l'envoi du signalement pour un id d'épigraphie + obtenir la liste de tous les signalements
- [ ] partie Backend : persistance du signalement dans la BDD

**Comment by Theo-Hafsaoui** [comment]
Ca me semble un peut trop gros, et pas essentielle
